# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: Hallo123_
    ports:
      - 5433:5432
    volumes:
      - devDiaryPgData:/var/lib/postgresql/data

volumes:
  devDiaryPgData: