# https://hub.docker.com/_/postgres <-- postgres image
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5430:5432
    volumes:
      - prodDiaryPgData:/var/lib/postgresql/data # the data from the path var/lib/postgresql/data will be stored in the volume prodDiaryPgData

  app:
    build: ./csharp-diary-rewrite # path to the Dockerfile to build the image
    image: <insertImageName>:<insertImageTag> # docker will check if this image exists, if not it will build it
    restart: always # restart the container if it crashes or if the system reboots or similar
    ports: 
      - 5000:80 # map the port 8080 from the container to the port 5000 on the host
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  prodDiaryPgData: